### PR TITLE
Implementation of the outer protocol

### PR DESCRIPTION
**Pull request by doudou**
It's a mix between Ublox sync characeters, CRC-CCITT for CRC and a
variable length integer field (honestly, the latter is probably
not needed, but it's TWO FULL BYTES SAVED ON SMALL PACKETS ;-)

### CODE REVIEW

**Comment by doudou** [comment]
@g-arjones: some context. The ARIEL project is dealing with integrating a drone with a USV. I'm planning to have a simple stateless UDP-based communication, where each side "blindly" published data about itself to the other. I was planning to use protobufs, having had a good time with them you-know-where ;-)

This would be the "generic" protocol as well as the documentation needed to create such a link from it. The actual implementation will lie in another package.

**Review by g-arjones — APPROVED** [review]

**Comment by g-arjones** [comment]
> having had a good time with them you-know-where ;-)

You and me both :-P

I've made a few changes to make that thing reusable.. Not sure what do you have in mind when you say the actual implementation will lie in another package but the design that proved to be a win for me:

- drivers-comms_protobuf:
  - Implements framing (what you just did);
  - Serializes and deserializes protobuf objects;
  - The classes that handles (de)serialization have to be templated because we don't know what the actual messages are at this point;
  - Provides cmake macros that will compile a .proto file and generate headers to be used by the client library

- Projects willing to use drivers-comms_protobuf (client library)
  - A minimal CMakeLists.txt that ideally just calls `comm_protobuf_generate(MessageName file.proto)`;
  - A .proto file

That's it, the client libraries are just two-file packages. I also wrap the generated headers in namespaces with cmake's `${PROJECT_NAME}` to prevent clashing if for some reason I have to use two different client libraries in the same binary (also because our convention says everything should be in a namespace with the name of the package ;)).

**Comment by doudou** [comment]
That's exactly what I had in mind... Only the CMake macros: CMake now has standard macros for protobuf. Anything that was missing ?

**Comment by g-arjones** [comment]
I have a header that is generated automatically with cmake's `configure_file()` so that the user can use the templated class without even knowing that it is a template (the generated header has a typedef with the template arguments). That's mostly the reason for the custom cmake macro

**Pull request merged**
